rm include/Utilities.h
rm include/JetCorrectionUncertainty.h
rm include/JetCorrectorParameters.h
rm include/JetCorrectorParametersHelper.h
rm include/JetResolution.h
rm include/JetResolutionObject.h
rm include/SimpleJetCorrectionUncertainty.h
rm include/SimpleJetCorrector.h
rm include/FactorizedJetCorrector.h
rm include/FactorizedJetCorrectorCalculator.h
rm include/FormulaEvaluator.h
rm src/JetCorrectionUncertainty.cc
rm src/JetCorrectorParameters.cc
rm src/JetCorrectorParametersHelper.cc
rm src/JetResolution.cc
rm src/JetResolutionObject.cc
rm src/SimpleJetCorrectionUncertainty.cc
rm src/SimpleJetCorrector.cc
rm src/FactorizedJetCorrector.cc
rm src/FactorizedJetCorrectorCalculator.cc
rm src/FormulaEvaluator.cc
rm src/formula*.h
rm src/formula*.cc
